[93mWARNING [0m:   DEPRECATED FEATURE: flwr.client.start_client() is deprecated.
	Instead, use the `flower-supernode` CLI command to start a SuperNode as shown below:

		$ flower-supernode --insecure --superlink='<IP>:<PORT>'

	To view all available options, run:

		$ flower-supernode --help

	Using `start_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.
        
[92mINFO [0m:      
[92mINFO [0m:      Received: train message 9cd2a5c5-2bea-40b2-bedb-a32964f9827d
[91mERROR [0m:     Client raised an exception.
Traceback (most recent call last):
  File "/home/mtheologitis/anaconda3/envs/flower/lib/python3.10/site-packages/flwr/client/app.py", line 572, in start_client_internal
    reply_message = client_app(message=message, context=context)
  File "/home/mtheologitis/anaconda3/envs/flower/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/mtheologitis/anaconda3/envs/flower/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/mtheologitis/anaconda3/envs/flower/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/mtheologitis/FDA-Opt-Sys/fdaopt/client.py", line 182, in <lambda>
    client_fn = lambda context: client_func(
  File "/home/mtheologitis/FDA-Opt-Sys/fdaopt/client.py", line 111, in client_func
    return FlowerClient(
  File "/home/mtheologitis/FDA-Opt-Sys/fdaopt/client.py", line 46, in __init__
    self.push_to_server_socket = create_push_socket(
  File "/home/mtheologitis/FDA-Opt-Sys/fdaopt/networking.py", line 11, in create_push_socket
    socket.connect(f"tcp://{ip}:{port}")
  File "/home/mtheologitis/anaconda3/envs/flower/lib/python3.10/site-packages/zmq/sugar/socket.py", line 337, in connect
    super().connect(addr)
  File "_zmq.py", line 949, in zmq.backend.cython._zmq.Socket.connect
  File "_zmq.py", line 179, in zmq.backend.cython._zmq._check_rc
zmq.error.ZMQError: Invalid argument (addr='tcp://localhost:localhost')
Traceback (most recent call last):
  File "/home/mtheologitis/anaconda3/envs/flower/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/mtheologitis/anaconda3/envs/flower/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/mtheologitis/FDA-Opt-Sys/fdaopt/client.py", line 204, in <module>
    start_client(
  File "/home/mtheologitis/anaconda3/envs/flower/lib/python3.10/site-packages/flwr/client/app.py", line 200, in start_client
    start_client_internal(
  File "/home/mtheologitis/anaconda3/envs/flower/lib/python3.10/site-packages/flwr/client/app.py", line 579, in start_client_internal
    raise ex
  File "/home/mtheologitis/anaconda3/envs/flower/lib/python3.10/site-packages/flwr/client/app.py", line 572, in start_client_internal
    reply_message = client_app(message=message, context=context)
  File "/home/mtheologitis/anaconda3/envs/flower/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/mtheologitis/anaconda3/envs/flower/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/mtheologitis/anaconda3/envs/flower/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/mtheologitis/FDA-Opt-Sys/fdaopt/client.py", line 182, in <lambda>
    client_fn = lambda context: client_func(
  File "/home/mtheologitis/FDA-Opt-Sys/fdaopt/client.py", line 111, in client_func
    return FlowerClient(
  File "/home/mtheologitis/FDA-Opt-Sys/fdaopt/client.py", line 46, in __init__
    self.push_to_server_socket = create_push_socket(
  File "/home/mtheologitis/FDA-Opt-Sys/fdaopt/networking.py", line 11, in create_push_socket
    socket.connect(f"tcp://{ip}:{port}")
  File "/home/mtheologitis/anaconda3/envs/flower/lib/python3.10/site-packages/zmq/sugar/socket.py", line 337, in connect
    super().connect(addr)
  File "_zmq.py", line 949, in zmq.backend.cython._zmq.Socket.connect
  File "_zmq.py", line 179, in zmq.backend.cython._zmq._check_rc
zmq.error.ZMQError: Invalid argument (addr='tcp://localhost:localhost')
